### ISSUE TITLE
Greetings from MMPose team!

### ISSUE THREAD

**Issue by ly015** [AlexTheBad/AP-10K#2]
Hi guys,

Thanks for this excellent work. Animal pose estimation is a field of great potentials and the AP-10K dataset would definitely benefit the research community.

We are currently maintaining [MMPose](https://github.com/open-mmlab/mmpose) project. We are glad to notice that MMPose has been used to benchmark algorithms on the AP-10K dataset. Hope you enjoyed it :). It has always been the purpose of OpenMMLab to facilitate computer vision research. 

And of course, all kinds of contributions from the community are mostly welcomed and would make OpenMMLab better. We have supported several datasets of animal pose estimation with a collection of pre-trained models in MMPose. We wonder if you would like to add AP-10K into MMPose and release the models in our [Model Zoo](https://mmpose.readthedocs.io/en/latest/modelzoo.html). It would provide a convenient way to access and use the AP-10K dataset, and also greatly complement MMPose.

Please let me know if you have any plans. My email is liyining0712@gmail.com

Best,
Yining Li

**Comment by AlexTheBad** [comment]
Thanks for the amazing MMPose project and your invitation. We'd like to add the AP-10k dataset into MMPose as well as release the pretrained models in your Model Zoo. We are now preparing the release version of them. Once everything is ready, we will contact you ASAP.
