### ISSUE TITLE
AP60K cannot be downloaded

### ISSUE THREAD

**Issue by Drow999** [AlexTheBad/AP-10K#8]
Hello,

I'm trying to download the ap60k data from the script, but it raised an error
![Screenshot from 2022-03-01 17-00-51](https://user-images.githubusercontent.com/77601118/156256327-abbe2931-337d-42ef-86e3-e753f0f918db.png) All of the images it downloaded are the image in the InternetImage folder. 
Can you run this script?

**Comment by AlexTheBad** [comment]
any images failed to be downloaded can be found in "organize_code.zip\Internet_images", just copy it to coresponding position!

**Comment by Drow999** [comment]
well, the fact is I cannot download any image. after I run the code, it just copy the image from Internet images to another directory. And the code, as you can see, would get stuck there all the time.

**Comment by AlexTheBad** [comment]
![image](https://user-images.githubusercontent.com/89204898/156398907-40763dd3-03de-47dc-bbac-6ccfe890bc12.png)
fix the organize.py as this then run it, we have prepare all the images you need to download in Internet images in case of image-links being invalid! so you don't need to run function "downloadAndOrganize()".  If you have any question about file path, please read the readme.txt carefully.
